LEARNING_RATE = 1e-4
BATCH_SIZE = 32
NUM_EPOCHS = 3
IMAGE_HEIGHT = 160  # 1280 originally
IMAGE_WIDTH = 240  # 1918 originally
PIN_MEMORY = True
LOAD_MODEL = False

# DataLoader parameters
TRAIN_SHUFFLE = True
VAL_SHUFFLE = False
TEST_SHUFFLE = False
TRAIN_DROP_LAST = True
VAL_DROP_LAST = True
TEST_DROP_LAST = False